actor End User 120 200
actor Admin 120 450
usecase Login 400 150
usecase Register 400 300
usecase Reset Password 400 450
usecase Manage Users 650 450
association End User Login
association End User Register
association End User Reset Password
association Admin Manage Users
association Admin Login
