'use strict';

const fs = require('fs');
const path = require('path');

/**
 * Ensure the .ombutocode/ directory structure exists in the target project.
 * Creates subdirectories, copies template files from APP_ROOT if not present,
 * and generates a .gitignore for runtime files.
 *
 * @param {string} projectRoot - The target project root directory
 * @param {string} appRoot - Ombuto Code's own installation directory
 */
function ensureOmbutocodeStructure(projectRoot, appRoot) {
  const ombutocodeDir = path.join(projectRoot, '.ombutocode');

  // Required subdirectories
  const subdirs = [
    'planning',
    'data',
    'data/tickets',
    'features',
    'templates',
    'codingagents',
    'logs',
    'run-output'
  ];

  for (const sub of subdirs) {
    const dirPath = path.join(ombutocodeDir, sub);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  }

  // Copy template files from APP_ROOT/.ombutocode/templates/ if not present
  const templateSrc = path.join(appRoot, '.ombutocode', 'templates');
  const templateDst = path.join(ombutocodeDir, 'templates');
  if (fs.existsSync(templateSrc)) {
    for (const file of fs.readdirSync(templateSrc)) {
      const src = path.join(templateSrc, file);
      const dst = path.join(templateDst, file);
      if (!fs.existsSync(dst) && fs.statSync(src).isFile()) {
        fs.copyFileSync(src, dst);
      }
    }
  }

  // Copy OMBUTOCODE_ENGINEERING_GUIDE.md to target .ombutocode/ if not present
  const guideSrc = path.join(appRoot, '.ombutocode', 'OMBUTOCODE_ENGINEERING_GUIDE.md');
  const guideDst = path.join(ombutocodeDir, 'OMBUTOCODE_ENGINEERING_GUIDE.md');
  if (fs.existsSync(guideSrc) && !fs.existsSync(guideDst)) {
    fs.copyFileSync(guideSrc, guideDst);
  }

  // Create empty backlog.yml from template if not present
  const backlogPath = path.join(ombutocodeDir, 'planning', 'backlog.yml');
  if (!fs.existsSync(backlogPath)) {
    const backlogTemplate = path.join(templateDst, 'backlog.yml');
    if (fs.existsSync(backlogTemplate)) {
      fs.copyFileSync(backlogTemplate, backlogPath);
    } else {
      // Minimal backlog if no template available
      fs.writeFileSync(backlogPath, 'version: 1\nupdated_at: ""\ntickets: []\n', 'utf8');
    }
  }

  // Create .ombutocode/.gitignore for runtime file exclusions
  const gitignorePath = path.join(ombutocodeDir, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    const gitignoreContent = [
      '# Runtime files (auto-generated by Ombuto Code)',
      'logs/',
      'run-output/',
      'codingagent-state.json',
      'data/*.db',
      'data/tickets/*.json',
      'data/tickets/*.tmp',
      'planning/archive.db',
      ''
    ].join('\n');
    fs.writeFileSync(gitignorePath, gitignoreContent, 'utf8');
  }
}

module.exports = { ensureOmbutocodeStructure };
