const test = require('node:test');
const assert = require('node:assert/strict');

const {
  normalizePromptPayload,
  buildCodexDraftPrompt,
  parseCodexDraftOutput,
  validateTicketDraft,
  generateNextAdHocId,
  buildTicketFromDraft,
  appendTicketToBacklog,
  createAdHocTicketCreator
} = require('../src/main/adHocTickets');

test('normalizePromptPayload validates prompt presence and length', () => {
  const empty = normalizePromptPayload({ promptText: '   ' });
  assert.equal(empty.ok, false);
  assert.equal(empty.error.code, 'VALIDATION_ERROR');

  const valid = normalizePromptPayload({ promptText: 'Create a quick cleanup task' });
  assert.equal(valid.ok, true);
  assert.equal(valid.promptText, 'Create a quick cleanup task');
});

test('buildCodexDraftPrompt embeds user input', () => {
  const prompt = buildCodexDraftPrompt('Need a ticket for refactoring');
  assert.match(prompt, /Return ONLY a JSON object/);
  assert.match(prompt, /Need a ticket for refactoring/);
});

test('parseCodexDraftOutput supports fenced JSON', () => {
  const parsed = parseCodexDraftOutput('```json\n{"title":"A","dependencies":[],"acceptance_criteria":["x"],"files_touched":[],"notes":"n"}\n```');
  assert.equal(parsed.title, 'A');
});

test('validateTicketDraft enforces required fields', () => {
  const normalized = validateTicketDraft({
    title: 'Test ticket',
    dependencies: ['X-1'],
    acceptance_criteria: ['Works'],
    files_touched: ['code/main.js'],
    notes: 'Draft note'
  });

  assert.equal(normalized.title, 'Test ticket');
  assert.deepEqual(normalized.dependencies, ['X-1']);

  assert.throws(
    () => validateTicketDraft({ title: 'Bad', dependencies: [], acceptance_criteria: [], files_touched: [], notes: 'x' }),
    /acceptance_criteria must contain at least 1 item/
  );
});

test('generateNextAdHocId increments from highest existing AD_HOC id', () => {
  const id = generateNextAdHocId([
    { id: 'AD_HOC-004' },
    { id: 'AD_HOC-010' },
    { id: 'OTHER-099' }
  ]);
  assert.equal(id, 'AD_HOC-011');
});

test('buildTicketFromDraft and appendTicketToBacklog enforce backlog defaults', () => {
  const nowIso = '2026-02-16T12:00:00.000Z';
  const ticket = buildTicketFromDraft({
    draft: {
      title: 'Generated task',
      dependencies: [],
      acceptance_criteria: ['A'],
      files_touched: [],
      notes: 'Generated by Codex'
    },
    existingTickets: [{ id: 'AD_HOC-001' }],
    promptText: 'Please create task',
    nowIso
  });

  assert.equal(ticket.id, 'AD_HOC-002');
  assert.equal(ticket.epic_ref, 'docs/Epics/feature_AD_HOC.md');
  assert.equal(ticket.status, 'backlog');
  assert.equal(ticket.eval_summary, null);

  const updated = appendTicketToBacklog({ version: 1, tickets: [] }, ticket, nowIso);
  assert.equal(updated.updated_at, '2026-02-16');
  assert.equal(updated.tickets.length, 1);
  assert.equal(updated.tickets[0].id, 'AD_HOC-002');
});

test('createAdHocTicketCreator rejects duplicate submit while a request is in flight', async () => {
  const writes = [];
  const creator = createAdHocTicketCreator({
    projectRoot: process.cwd(),
    resolveTemplateConfig: () => ({ command: 'codex', args: [] }),
    runDraftCommand: async () => {
      await new Promise((resolve) => setTimeout(resolve, 40));
      return {
        stdout: JSON.stringify({
          title: 'Generated from prompt',
          dependencies: [],
          acceptance_criteria: ['Works'],
          files_touched: [],
          notes: 'Drafted'
        }),
        stderr: ''
      };
    },
    readBacklogData: () => ({ version: 1, updated_at: '', tickets: [] }),
    writeBacklogData: (data) => writes.push(data),
    now: () => '2026-02-16T12:20:00.000Z'
  });

  const first = creator({ promptText: 'Create one ticket please' });
  const second = await creator({ promptText: 'Second click quickly' });

  assert.equal(second.success, false);
  assert.equal(second.error.code, 'REQUEST_IN_FLIGHT');

  const firstResult = await first;
  assert.equal(firstResult.success, true);
  assert.equal(writes.length, 1);
  assert.equal(writes[0].tickets.length, 1);
});

test('createAdHocTicketCreator returns structured failure and preserves backlog on draft errors', async () => {
  const writes = [];
  const creator = createAdHocTicketCreator({
    projectRoot: process.cwd(),
    resolveTemplateConfig: () => ({ command: 'codex', args: [] }),
    runDraftCommand: async () => ({ stdout: '{"title":"Missing required fields"}', stderr: '' }),
    readBacklogData: () => ({ version: 1, updated_at: '', tickets: [] }),
    writeBacklogData: (data) => writes.push(data),
    now: () => '2026-02-16T12:20:00.000Z'
  });

  const result = await creator({ promptText: 'This should fail validation' });
  assert.equal(result.success, false);
  assert.equal(result.error.code, 'AGENT_DRAFT_FAILED');
  assert.equal(writes.length, 0);
});

test('createAdHocTicketCreator uses configured ad hoc agent selection', async () => {
  let selectedAgent = null;
  const creator = createAdHocTicketCreator({
    projectRoot: process.cwd(),
    readAdHocTicketAgent: () => 'kimi',
    resolveTemplateConfig: (_projectRoot, agentName) => {
      selectedAgent = agentName;
      return { command: 'kimi', args: [] };
    },
    runDraftCommand: async () => ({
      stdout: JSON.stringify({
        title: 'Generated from prompt',
        dependencies: [],
        acceptance_criteria: ['Works'],
        files_touched: [],
        notes: 'Drafted'
      }),
      stderr: ''
    }),
    readBacklogData: () => ({ version: 1, updated_at: '', tickets: [] }),
    writeBacklogData: () => {},
    now: () => '2026-02-16T12:20:00.000Z'
  });

  const result = await creator({ promptText: 'Create one ticket please' });
  assert.equal(result.success, true);
  assert.equal(selectedAgent, 'kimi');
});
